### ISSUE TITLE
Add Links to AUR (Arch User Repository)

### ISSUE THREAD

**Issue by w568w** [simon816/libtar-twrp#1]
Hello,

I have been searching for how to extract files from my TWRP backups for a long time until reading your comments in <https://github.com/TeamWin/Team-Win-Recovery-Project/issues/1618#issuecomment-1738265626> introducing your patched version of `libtar`. It is wonderful. Thanks for your work!

To help others compile & install this tool with ease, I have just created a new Arch user package, [`libtar-twrp-git`](https://aur.archlinux.org/packages/libtar-twrp-git). Anyone with Arch Build System can pull source codes from your repository, build and install `libtar` with one line:

```sh
# Any AUR helper, e.g. yay, paru
$ yay -S libtar-twrp-git
```

Would you mind adding these instructions to README or somewhere else?

**Comment by simon816** [comment]
Thanks for packaging this! I'll create a custom README for this repo and add that to it
